version: '3'

services:

  app:
    build: 
      context: node
    image: gustavolopesv3/node-with-nginx
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 10s node src/index.js
    networks:
      - node-network
    tty: true
    volumes: 
      - ./node/src/:/usr/src/app/src
      - ./node/package.json:/usr/src/app/package.json
      - ./node/package-lock.json:/usr/src/app/package-lock.json
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
    image: brunoan99/nginx:prod
    container_name: nginx
    networks:
      - node-network
    ports: 
      - 8080:80
    depends_on:
      - app

networks:
  node-network:
    driver: bridge